# Artificial Neural Network

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.1.0'

## Part 1 - Data Preprocessing

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

In [12]:
ann = tf.keras.models.Sequential()

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 5s 617us/sample - loss: 0.5435 - accuracy: 0.7950
Epoch 2/100
8000/8000 [==============================] - 1s 88us/sample - loss: 0.4775 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 97us/sample - loss: 0.4567 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 78us/sample - loss: 0.4458 - accuracy: 0.7960
Epoch 5/100
8000/8000 [==============================] - 1s 77us/sample - loss: 0.4382 - accuracy: 0.7960
Epoch 6/100
8000/8000 [==============================] - 1s 73us/sample - loss: 0.4327 - accuracy: 0.7960
Epoch 7/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.4289 - accuracy: 0.7960
Epoch 8/100
8000/8000 [==============================] - 1s 97us/sample - loss: 0.4255 - accuracy: 0.7960
Epoch 9/100
8000/8000 [==============================] - 1s 75us/sample - loss: 0.4227 - accuracy: 0.7960
Epoch 10/100
8000/8000 

8000/8000 [==============================] - 1s 71us/sample - loss: 0.3342 - accuracy: 0.8662
Epoch 77/100
8000/8000 [==============================] - 1s 67us/sample - loss: 0.3343 - accuracy: 0.8648
Epoch 78/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3340 - accuracy: 0.8646
Epoch 79/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3339 - accuracy: 0.8654
Epoch 80/100
8000/8000 [==============================] - 1s 74us/sample - loss: 0.3338 - accuracy: 0.8654
Epoch 81/100
8000/8000 [==============================] - 1s 71us/sample - loss: 0.3338 - accuracy: 0.8654
Epoch 82/100
8000/8000 [==============================] - 1s 70us/sample - loss: 0.3339 - accuracy: 0.8648
Epoch 83/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3338 - accuracy: 0.8643
Epoch 84/100
8000/8000 [==============================] - 1s 69us/sample - loss: 0.3336 - accuracy: 0.8650
Epoch 85/100
8000/8000 [==========================

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


In [21]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1515   80]
 [ 195  210]]


0.8625